language: java

services: 
 - java

script: 
 - docker build -t cpecanevaal/sample-application-db-changelog-job ./sample-application-db-changelog-job/
 - docker build -t cpecanevaal/sample-application-http-api-server ./sample-application-http-api-server/
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push cpecanevaal/sample-application-db-changelog-job
 - docker push cpecanevaal/sample-application-http-api-server
 - mvn verify sonar:sonar
 
